//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Phone", Namespace="http://PKA.by/")]
    public partial class Phone : object
    {
        
        private int IdField;
        
        private string NameField;
        
        private int NumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://PKA.by/", ConfigurationName="ServiceReference1.WebServicePhoneBookSoap")]
    public interface WebServicePhoneBookSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PKA.by/GetDict", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetDictResponse> GetDictAsync(ServiceReference1.GetDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PKA.by/AddDict", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.AddDictResponse> AddDictAsync(ServiceReference1.AddDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PKA.by/UpdDict", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.UpdDictResponse> UpdDictAsync(ServiceReference1.UpdDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PKA.by/DelDict", ReplyAction="*")]
        System.Threading.Tasks.Task DelDictAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDict", Namespace="http://PKA.by/", Order=0)]
        public ServiceReference1.GetDictRequestBody Body;
        
        public GetDictRequest()
        {
        }
        
        public GetDictRequest(ServiceReference1.GetDictRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDictRequestBody
    {
        
        public GetDictRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDictResponse", Namespace="http://PKA.by/", Order=0)]
        public ServiceReference1.GetDictResponseBody Body;
        
        public GetDictResponse()
        {
        }
        
        public GetDictResponse(ServiceReference1.GetDictResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://PKA.by/")]
    public partial class GetDictResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ServiceReference1.Phone> GetDictResult;
        
        public GetDictResponseBody()
        {
        }
        
        public GetDictResponseBody(System.Collections.Generic.List<ServiceReference1.Phone> GetDictResult)
        {
            this.GetDictResult = GetDictResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDictRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDict", Namespace="http://PKA.by/", Order=0)]
        public ServiceReference1.AddDictRequestBody Body;
        
        public AddDictRequest()
        {
        }
        
        public AddDictRequest(ServiceReference1.AddDictRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://PKA.by/")]
    public partial class AddDictRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.Phone phone;
        
        public AddDictRequestBody()
        {
        }
        
        public AddDictRequestBody(ServiceReference1.Phone phone)
        {
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDictResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDictResponse", Namespace="http://PKA.by/", Order=0)]
        public ServiceReference1.AddDictResponseBody Body;
        
        public AddDictResponse()
        {
        }
        
        public AddDictResponse(ServiceReference1.AddDictResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddDictResponseBody
    {
        
        public AddDictResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdDictRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdDict", Namespace="http://PKA.by/", Order=0)]
        public ServiceReference1.UpdDictRequestBody Body;
        
        public UpdDictRequest()
        {
        }
        
        public UpdDictRequest(ServiceReference1.UpdDictRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://PKA.by/")]
    public partial class UpdDictRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.Phone phone;
        
        public UpdDictRequestBody()
        {
        }
        
        public UpdDictRequestBody(ServiceReference1.Phone phone)
        {
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdDictResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdDictResponse", Namespace="http://PKA.by/", Order=0)]
        public ServiceReference1.UpdDictResponseBody Body;
        
        public UpdDictResponse()
        {
        }
        
        public UpdDictResponse(ServiceReference1.UpdDictResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdDictResponseBody
    {
        
        public UpdDictResponseBody()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface WebServicePhoneBookSoapChannel : ServiceReference1.WebServicePhoneBookSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class WebServicePhoneBookSoapClient : System.ServiceModel.ClientBase<ServiceReference1.WebServicePhoneBookSoap>, ServiceReference1.WebServicePhoneBookSoap
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebServicePhoneBookSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebServicePhoneBookSoapClient.GetBindingForEndpoint(endpointConfiguration), WebServicePhoneBookSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServicePhoneBookSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebServicePhoneBookSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServicePhoneBookSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebServicePhoneBookSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServicePhoneBookSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }

        public WebServicePhoneBookSoapClient()
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetDictResponse> ServiceReference1.WebServicePhoneBookSoap.GetDictAsync(ServiceReference1.GetDictRequest request)
        {
            return base.Channel.GetDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetDictResponse> GetDictAsync()
        {
            ServiceReference1.GetDictRequest inValue = new ServiceReference1.GetDictRequest();
            inValue.Body = new ServiceReference1.GetDictRequestBody();
            return ((ServiceReference1.WebServicePhoneBookSoap)(this)).GetDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.AddDictResponse> ServiceReference1.WebServicePhoneBookSoap.AddDictAsync(ServiceReference1.AddDictRequest request)
        {
            return base.Channel.AddDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AddDictResponse> AddDictAsync(ServiceReference1.Phone phone)
        {
            ServiceReference1.AddDictRequest inValue = new ServiceReference1.AddDictRequest();
            inValue.Body = new ServiceReference1.AddDictRequestBody();
            inValue.Body.phone = phone;
            return ((ServiceReference1.WebServicePhoneBookSoap)(this)).AddDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.UpdDictResponse> ServiceReference1.WebServicePhoneBookSoap.UpdDictAsync(ServiceReference1.UpdDictRequest request)
        {
            return base.Channel.UpdDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.UpdDictResponse> UpdDictAsync(ServiceReference1.Phone phone)
        {
            ServiceReference1.UpdDictRequest inValue = new ServiceReference1.UpdDictRequest();
            inValue.Body = new ServiceReference1.UpdDictRequestBody();
            inValue.Body.phone = phone;
            return ((ServiceReference1.WebServicePhoneBookSoap)(this)).UpdDictAsync(inValue);
        }
        
        public System.Threading.Tasks.Task DelDictAsync(int id)
        {
            return base.Channel.DelDictAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServicePhoneBookSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServicePhoneBookSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServicePhoneBookSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44386/WebServicePhoneBook.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServicePhoneBookSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44386/WebServicePhoneBook.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebServicePhoneBookSoap,
            
            WebServicePhoneBookSoap12,
        }
    }
}
