//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Phone", Namespace="http://PKA.by/")]
    [System.SerializableAttribute()]
    public partial class Phone : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://PKA.by/", ConfigurationName="ServiceReference.WebServicePhoneBookSoap")]
    public interface WebServicePhoneBookSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем GetDictResult из пространства имен http://PKA.by/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://PKA.by/GetDict", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference.GetDictResponse GetDict(WindowsFormsApp1.ServiceReference.GetDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PKA.by/GetDict", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference.GetDictResponse> GetDictAsync(WindowsFormsApp1.ServiceReference.GetDictRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем phone из пространства имен http://PKA.by/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://PKA.by/AddDict", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference.AddDictResponse AddDict(WindowsFormsApp1.ServiceReference.AddDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PKA.by/AddDict", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference.AddDictResponse> AddDictAsync(WindowsFormsApp1.ServiceReference.AddDictRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем phone из пространства имен http://PKA.by/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://PKA.by/UpdDict", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference.UpdDictResponse UpdDict(WindowsFormsApp1.ServiceReference.UpdDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PKA.by/UpdDict", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference.UpdDictResponse> UpdDictAsync(WindowsFormsApp1.ServiceReference.UpdDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PKA.by/DelDict", ReplyAction="*")]
        void DelDict(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PKA.by/DelDict", ReplyAction="*")]
        System.Threading.Tasks.Task DelDictAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDict", Namespace="http://PKA.by/", Order=0)]
        public WindowsFormsApp1.ServiceReference.GetDictRequestBody Body;
        
        public GetDictRequest() {
        }
        
        public GetDictRequest(WindowsFormsApp1.ServiceReference.GetDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDictRequestBody {
        
        public GetDictRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDictResponse", Namespace="http://PKA.by/", Order=0)]
        public WindowsFormsApp1.ServiceReference.GetDictResponseBody Body;
        
        public GetDictResponse() {
        }
        
        public GetDictResponse(WindowsFormsApp1.ServiceReference.GetDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://PKA.by/")]
    public partial class GetDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceReference.Phone[] GetDictResult;
        
        public GetDictResponseBody() {
        }
        
        public GetDictResponseBody(WindowsFormsApp1.ServiceReference.Phone[] GetDictResult) {
            this.GetDictResult = GetDictResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDict", Namespace="http://PKA.by/", Order=0)]
        public WindowsFormsApp1.ServiceReference.AddDictRequestBody Body;
        
        public AddDictRequest() {
        }
        
        public AddDictRequest(WindowsFormsApp1.ServiceReference.AddDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://PKA.by/")]
    public partial class AddDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceReference.Phone phone;
        
        public AddDictRequestBody() {
        }
        
        public AddDictRequestBody(WindowsFormsApp1.ServiceReference.Phone phone) {
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDictResponse", Namespace="http://PKA.by/", Order=0)]
        public WindowsFormsApp1.ServiceReference.AddDictResponseBody Body;
        
        public AddDictResponse() {
        }
        
        public AddDictResponse(WindowsFormsApp1.ServiceReference.AddDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddDictResponseBody {
        
        public AddDictResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdDict", Namespace="http://PKA.by/", Order=0)]
        public WindowsFormsApp1.ServiceReference.UpdDictRequestBody Body;
        
        public UpdDictRequest() {
        }
        
        public UpdDictRequest(WindowsFormsApp1.ServiceReference.UpdDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://PKA.by/")]
    public partial class UpdDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceReference.Phone phone;
        
        public UpdDictRequestBody() {
        }
        
        public UpdDictRequestBody(WindowsFormsApp1.ServiceReference.Phone phone) {
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdDictResponse", Namespace="http://PKA.by/", Order=0)]
        public WindowsFormsApp1.ServiceReference.UpdDictResponseBody Body;
        
        public UpdDictResponse() {
        }
        
        public UpdDictResponse(WindowsFormsApp1.ServiceReference.UpdDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdDictResponseBody {
        
        public UpdDictResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicePhoneBookSoapChannel : WindowsFormsApp1.ServiceReference.WebServicePhoneBookSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicePhoneBookSoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference.WebServicePhoneBookSoap>, WindowsFormsApp1.ServiceReference.WebServicePhoneBookSoap {
        
        public WebServicePhoneBookSoapClient() {
        }
        
        public WebServicePhoneBookSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicePhoneBookSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePhoneBookSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePhoneBookSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference.GetDictResponse WindowsFormsApp1.ServiceReference.WebServicePhoneBookSoap.GetDict(WindowsFormsApp1.ServiceReference.GetDictRequest request) {
            return base.Channel.GetDict(request);
        }
        
        public WindowsFormsApp1.ServiceReference.Phone[] GetDict() {
            WindowsFormsApp1.ServiceReference.GetDictRequest inValue = new WindowsFormsApp1.ServiceReference.GetDictRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference.GetDictRequestBody();
            WindowsFormsApp1.ServiceReference.GetDictResponse retVal = ((WindowsFormsApp1.ServiceReference.WebServicePhoneBookSoap)(this)).GetDict(inValue);
            return retVal.Body.GetDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference.GetDictResponse> WindowsFormsApp1.ServiceReference.WebServicePhoneBookSoap.GetDictAsync(WindowsFormsApp1.ServiceReference.GetDictRequest request) {
            return base.Channel.GetDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference.GetDictResponse> GetDictAsync() {
            WindowsFormsApp1.ServiceReference.GetDictRequest inValue = new WindowsFormsApp1.ServiceReference.GetDictRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference.GetDictRequestBody();
            return ((WindowsFormsApp1.ServiceReference.WebServicePhoneBookSoap)(this)).GetDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference.AddDictResponse WindowsFormsApp1.ServiceReference.WebServicePhoneBookSoap.AddDict(WindowsFormsApp1.ServiceReference.AddDictRequest request) {
            return base.Channel.AddDict(request);
        }
        
        public void AddDict(WindowsFormsApp1.ServiceReference.Phone phone) {
            WindowsFormsApp1.ServiceReference.AddDictRequest inValue = new WindowsFormsApp1.ServiceReference.AddDictRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference.AddDictRequestBody();
            inValue.Body.phone = phone;
            WindowsFormsApp1.ServiceReference.AddDictResponse retVal = ((WindowsFormsApp1.ServiceReference.WebServicePhoneBookSoap)(this)).AddDict(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference.AddDictResponse> WindowsFormsApp1.ServiceReference.WebServicePhoneBookSoap.AddDictAsync(WindowsFormsApp1.ServiceReference.AddDictRequest request) {
            return base.Channel.AddDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference.AddDictResponse> AddDictAsync(WindowsFormsApp1.ServiceReference.Phone phone) {
            WindowsFormsApp1.ServiceReference.AddDictRequest inValue = new WindowsFormsApp1.ServiceReference.AddDictRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference.AddDictRequestBody();
            inValue.Body.phone = phone;
            return ((WindowsFormsApp1.ServiceReference.WebServicePhoneBookSoap)(this)).AddDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference.UpdDictResponse WindowsFormsApp1.ServiceReference.WebServicePhoneBookSoap.UpdDict(WindowsFormsApp1.ServiceReference.UpdDictRequest request) {
            return base.Channel.UpdDict(request);
        }
        
        public void UpdDict(WindowsFormsApp1.ServiceReference.Phone phone) {
            WindowsFormsApp1.ServiceReference.UpdDictRequest inValue = new WindowsFormsApp1.ServiceReference.UpdDictRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference.UpdDictRequestBody();
            inValue.Body.phone = phone;
            WindowsFormsApp1.ServiceReference.UpdDictResponse retVal = ((WindowsFormsApp1.ServiceReference.WebServicePhoneBookSoap)(this)).UpdDict(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference.UpdDictResponse> WindowsFormsApp1.ServiceReference.WebServicePhoneBookSoap.UpdDictAsync(WindowsFormsApp1.ServiceReference.UpdDictRequest request) {
            return base.Channel.UpdDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference.UpdDictResponse> UpdDictAsync(WindowsFormsApp1.ServiceReference.Phone phone) {
            WindowsFormsApp1.ServiceReference.UpdDictRequest inValue = new WindowsFormsApp1.ServiceReference.UpdDictRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference.UpdDictRequestBody();
            inValue.Body.phone = phone;
            return ((WindowsFormsApp1.ServiceReference.WebServicePhoneBookSoap)(this)).UpdDictAsync(inValue);
        }
        
        public void DelDict(int id) {
            base.Channel.DelDict(id);
        }
        
        public System.Threading.Tasks.Task DelDictAsync(int id) {
            return base.Channel.DelDictAsync(id);
        }
    }
}
