//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Phone", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Phone : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPhone")]
    public interface IPhone {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhone/GetPhones", ReplyAction="http://tempuri.org/IPhone/GetPhonesResponse")]
        WindowsFormsApp1.ServiceReference1.Phone[] GetPhones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhone/GetPhones", ReplyAction="http://tempuri.org/IPhone/GetPhonesResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Phone[]> GetPhonesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhone/UpdatePhone", ReplyAction="http://tempuri.org/IPhone/UpdatePhoneResponse")]
        void UpdatePhone(WindowsFormsApp1.ServiceReference1.Phone phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhone/UpdatePhone", ReplyAction="http://tempuri.org/IPhone/UpdatePhoneResponse")]
        System.Threading.Tasks.Task UpdatePhoneAsync(WindowsFormsApp1.ServiceReference1.Phone phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhone/DeletePhone", ReplyAction="http://tempuri.org/IPhone/DeletePhoneResponse")]
        void DeletePhone(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhone/DeletePhone", ReplyAction="http://tempuri.org/IPhone/DeletePhoneResponse")]
        System.Threading.Tasks.Task DeletePhoneAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhone/AddPhone", ReplyAction="http://tempuri.org/IPhone/AddPhoneResponse")]
        void AddPhone(WindowsFormsApp1.ServiceReference1.Phone phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhone/AddPhone", ReplyAction="http://tempuri.org/IPhone/AddPhoneResponse")]
        System.Threading.Tasks.Task AddPhoneAsync(WindowsFormsApp1.ServiceReference1.Phone phone);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhoneChannel : WindowsFormsApp1.ServiceReference1.IPhone, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhoneClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.IPhone>, WindowsFormsApp1.ServiceReference1.IPhone {
        
        public PhoneClient() {
        }
        
        public PhoneClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhoneClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsFormsApp1.ServiceReference1.Phone[] GetPhones() {
            return base.Channel.GetPhones();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Phone[]> GetPhonesAsync() {
            return base.Channel.GetPhonesAsync();
        }
        
        public void UpdatePhone(WindowsFormsApp1.ServiceReference1.Phone phone) {
            base.Channel.UpdatePhone(phone);
        }
        
        public System.Threading.Tasks.Task UpdatePhoneAsync(WindowsFormsApp1.ServiceReference1.Phone phone) {
            return base.Channel.UpdatePhoneAsync(phone);
        }
        
        public void DeletePhone(int id) {
            base.Channel.DeletePhone(id);
        }
        
        public System.Threading.Tasks.Task DeletePhoneAsync(int id) {
            return base.Channel.DeletePhoneAsync(id);
        }
        
        public void AddPhone(WindowsFormsApp1.ServiceReference1.Phone phone) {
            base.Channel.AddPhone(phone);
        }
        
        public System.Threading.Tasks.Task AddPhoneAsync(WindowsFormsApp1.ServiceReference1.Phone phone) {
            return base.Channel.AddPhoneAsync(phone);
        }
    }
}
